language: node_js

jobs:
  include:
    - node_js: stable
      name: Check linting
      script: npm run test:lint
    - node_js: stable
      name: Check types
      script: npm run test:types
    - node_js: stable
      name: Test on stable Node.js
      script: npm run test:mocha
      before_deploy:
        - cd example && npm install && cd ..
        - mkdir _deploy
        - cp example/bundle.js example/index.html _deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: _deploy
        on:
          branch: master
    - node_js: 12
      name: Test on Node.js 12
      script: npm run test:mocha
    - node_js: 10
      name: Test on Node.js 10
      script: npm run test:mocha
